version: '3'

services:
  aplikasi_web_di_dalam_docker:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --reload "aplikasi_web.aplikasi:bikin_aplikasi()"

    volumes:
      - '.:/aplikasi_web_docker'

    ports:
      - '8989:8000'


  service_postgresql_di_dalam_docker:
    image: 'postgres:9.6'

    environment:
      POSTGRES_USER: 'cms1'
      POSTGRES_PASSWORD: '12345'

    volumes:
      - '/var/lib/postgresql/data'

    ports:
      - '5433:5432'
